### ISSUE TITLE
[server] TypeError domain.enter is not a function

### ISSUE THREAD

**Issue by leoek** [berstend/hypertunnel#3]
Error:
```
root@myserver:/# hypertunnel-server -p 3000 -t test --domain mydomain.test  
(node:49) UnhandledPromiseRejectionWarning: TypeError: domain.enter is not a function
    at Command.emit (events.js:199:12)
    at Command.parseOptions (/usr/local/lib/node_modules/hypertunnel-server/node_modules/commander/index.js:739:14)
    at Command.parse (/usr/local/lib/node_modules/hypertunnel-server/node_modules/commander/index.js:471:21)
    at Module.module.exports (/usr/local/lib/node_modules/hypertunnel-server/cli.js:15:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/hypertunnel-server/cli.js:33:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
(node:49) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:49) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Node: v8.16.0

`hypertunnel-server --version` outputs the same:
```
root@631af25ebee2:/# hypertunnel-server --version
(node:56) UnhandledPromiseRejectionWarning: TypeError: domain.enter is not a function
    at Command.emit (events.js:199:12)
    at Command.parseOptions (/usr/local/lib/node_modules/hypertunnel-server/node_modules/commander/index.js:742:14)
    at Command.parse (/usr/local/lib/node_modules/hypertunnel-server/node_modules/commander/index.js:471:21)
    at Module.module.exports (/usr/local/lib/node_modules/hypertunnel-server/cli.js:15:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/hypertunnel-server/cli.js:33:8)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
(node:56) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:56) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by leoek** [comment]
Apparently the issue is gone with a newer node version (12.x)
