### ISSUE TITLE
ETIMEDOUT hypertunnel.ga

### ISSUE THREAD

**Issue by matthieupinte** [berstend/hypertunnel#4]
Seems to be down ?

```
> npx hypertunnel --port 4040

      An unexpected error occured.

      Please report this issue at: https://github.com/berstend/hypertunnel/issues

{ RequestError: connect ETIMEDOUT 195.20.53.124:443
    at ClientRequest.req.once.err (/usr/local/lib/node_modules/hypertunnel/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:285:13)
    at ClientRequest.emit (events.js:197:13)
    at TLSSocket.socketErrorListener (_http_client.js:397:9)
    at TLSSocket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
  name: 'RequestError',
  code: 'ETIMEDOUT',
  host: 'hypertunnel.ga',
  hostname: 'hypertunnel.ga',
  method: 'POST',
  path: '/create',
  protocol: 'https:',
  url: 'https://hypertunnel.ga/create' }
```

**Comment by elhamsarikhani** [comment]
+1

**Comment by skmd87** [comment]
+1

**Comment by Omena0** [comment]
+1

**Comment by lotaylor1** [comment]
+1
